In [1]:
import pandas as pd

In [8]:
sept_data = pd.read_csv("202309-citibike-tripdata.csv",low_memory=False)
oct_data = pd.read_csv("202310-citibike-tripdata.csv",low_memory=False)
nov_data = pd.read_csv("202311-citibike-tripdata.csv",low_memory=False)

In [9]:
fall_data = [sept_data,oct_data,nov_data]
fall_df = pd.concat(fall_data)
fall_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B0A0F1DEFA4B72FC,electric_bike,2023-09-03 10:20:41,2023-09-03 10:24:16,E 1 St & Bowery,5636.13,E 10 St & 2 Ave,5746.02,40.724861,-73.992131,40.729708,-73.986598,member
1,2B26AB15647BF4EE,classic_bike,2023-09-27 15:44:23,2023-09-27 15:53:25,Pearl St & Hanover Square,4993.02,Allen St & Rivington St,5414.06,40.704650,-74.009133,40.720196,-73.989978,member
2,9D2B5971CA4E513F,classic_bike,2023-09-19 13:40:48,2023-09-19 13:48:11,E 1 St & Bowery,5636.13,E 10 St & 2 Ave,5746.02,40.724753,-73.992116,40.729708,-73.986598,member
3,17E6760596DC3ABE,classic_bike,2023-09-30 16:27:50,2023-09-30 16:56:35,Central Ave & Himrod St,4713.01,Mott St & Prince St,5561.04,40.696706,-73.922935,40.723180,-73.994800,member
4,97EFF376A7E2DC70,classic_bike,2023-09-21 16:59:53,2023-09-21 17:07:36,St Marks Pl & 2 Ave,5669.10,Mott St & Prince St,5561.04,40.728419,-73.987140,40.723180,-73.994800,member

In [10]:
fall_df.to_csv('fall_citi_data.csv')